/**
 * ServiceBook Pros Integration Service
 * Pushes estimates to Knack API
 */

const axios = require('axios');

class ServiceBookIntegration {
  
  /**
   * Push estimate to ServiceBook Pros (Knack)
   */
  async pushEstimate(estimate, apiKey, appId) {
    try {
      const lineItems = JSON.parse(estimate.line_items);

      // Create Estimate in Knack
      const estimateData = {
        field_148: new Date().toISOString(), // Estimate Date
        field_150: estimate.subtotal, // Subtotal
        field_151: 8, // Tax Rate (default 8%)
        field_152: estimate.tax, // Tax Amount
        field_153: estimate.total, // Total Amount
        field_154: 'Generated by EstimatorAI', // Terms & Conditions
        field_51: 'Draft', // Status
        // Add other fields as needed
      };

      const estimateResponse = await axios.post(
        `https://api.knack.com/v1/objects/object_7/records`,
        estimateData,
        {
          headers: {
            'X-Knack-Application-Id': appId,
            'X-Knack-REST-API-Key': apiKey,
            'Content-Type': 'application/json'
          }
        }
      );

      const knackEstimateId = estimateResponse.data.id;

      // Create Estimate Line Items
      for (const item of lineItems) {
        await this.createLineItem(item, knackEstimateId, apiKey, appId);
      }

      return knackEstimateId;

    } catch (error) {
      console.error('Error pushing to ServiceBook:', error.response?.data || error.message);
      throw new Error('Failed to push estimate to ServiceBook Pros');
    }
  }

  /**
   * Create line item in Knack
   */
  async createLineItem(item, estimateId, apiKey, appId) {
    // Assuming Estimate Line Items object exists (created in Phase 1)
    const lineItemData = {
      field_description: item.description, // Adjust field keys as needed
      field_quantity: item.quantity,
      field_unit: item.unit,
      field_rate: item.rate,
      field_total: item.total,
      field_estimate_connection: estimateId // Connection to Estimate
    };

    await axios.post(
      `https://api.knack.com/v1/objects/object_estimate_line_items/records`,
      lineItemData,
      {
        headers: {
          'X-Knack-Application-Id': appId,
          'X-Knack-REST-API-Key': apiKey,
          'Content-Type': 'application/json'
        }
      }
    );
  }

  /**
   * Pull pricing rules from ServiceBook Pros
   */
  async getPricingRules(apiKey, appId, userId) {
    try {
      // Get user's pricing configuration from ServiceBook
      const response = await axios.get(
        `https://api.knack.com/v1/objects/object_users/records/${userId}`,
        {
          headers: {
            'X-Knack-Application-Id': appId,
            'X-Knack-REST-API-Key': apiKey
          }
        }
      );

      return {
        laborRate: response.data.field_labor_rate || 75,
        materialMarkup: response.data.field_material_markup || 0.25,
        taxRate: response.data.field_tax_rate || 0.08,
        regionalMultiplier: response.data.field_regional_multiplier || 1.0
      };

    } catch (error) {
      console.error('Error fetching pricing rules:', error);
      return null;
    }
  }

  /**
   * Verify ServiceBook integration is valid
   */
  async verifyIntegration(apiKey, appId) {
    try {
      const response = await axios.get(
        `https://api.knack.com/v1/objects`,
        {
          headers: {
            'X-Knack-Application-Id': appId,
            'X-Knack-REST-API-Key': apiKey
          }
        }
      );

      return response.status === 200;

    } catch (error) {
      return false;
    }
  }
}

module.exports = new ServiceBookIntegration();
